language: node_js
sudo: true

before_install:
  - gem install sass
  - gem install compass

matrix:
  include:
    - node_js: "4.4.5"
      env: JOB=unittest
    - node_js: "4.4.5"
      env: JOB=eslint
  allow_failures:
    - node_js: "4.4.5"
      env: JOB=eslint

before_script:
  - npm install -g bower grunt
  - bower install

script:
  - ./scripts/build.sh
