language: node_js

before_install:
  - gem install sass
  - gem install compass

node_js:
  - "4.4.5"

matrix:
  include:
    - env: JOB=unittest
  allow_failures:
    - env: JOB=eslint

before_script:
  - npm install -g bower grunt
  - bower install

script:
  - ./scripts/build.sh
